CREATE TABLE EMPLOYEE (
	ID INTEGER NOT NULL,
	NAME CHAR(5) NOT NULL,
	MANAGER INTEGER,
	PRIMARY KEY (ID)
);


INSERT INTO EMPLOYEE(ID, NAME, MANAGER)
VALUES
(1, 'RAHUL', 2),
(2, 'RAVI', 3),
(3, 'MAITY', NULL),
(4, 'DEEP', 3),
(5, 'SUME', 2);


SELECT F.NAME, COUNT(*) FROM EMPLOYEE E, EMPLOYEE F WHERE E.MANAGER = F.ID GROUP BY F.NAME HAVING F.NAME = 'RAVI';
